#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const root = path.join(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

let commit = 'local';
try {
  commit = execSync('git rev-parse --short HEAD', { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] })
    .toString()
    .trim();
} catch {
  // git not available in CI-less builds
}

const payload = {
  version: pkg.version,
  builtAt: new Date().toISOString(),
  commit,
};

const publicPath = path.join(root, 'public', 'version.json');
fs.mkdirSync(path.dirname(publicPath), { recursive: true });
fs.writeFileSync(publicPath, JSON.stringify(payload, null, 2) + '\n');

const generatedDir = path.join(root, 'src', 'generated');
fs.mkdirSync(generatedDir, { recursive: true });
fs.writeFileSync(
  path.join(generatedDir, 'appVersion.ts'),
  `// Auto-generated by scripts/write-version.js — do not edit\nexport const APP_BUILD = ${JSON.stringify(payload)} as const;\n`
);

// electron-builder reads version from electron/package.json — keep in sync.
const electronPkgPath = path.join(root, 'electron', 'package.json');
const electronPkg = JSON.parse(fs.readFileSync(electronPkgPath, 'utf8'));
electronPkg.version = pkg.version;
fs.writeFileSync(electronPkgPath, JSON.stringify(electronPkg, null, 2) + '\n');

console.log(`Wrote app version ${payload.version} (${payload.commit})`);
